version: '3.7'

services:

  # Servidor
  zabbix-server-mysql:
    container_name: zabbix-server-mysql
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${ZBX_SERVER_PORT}:10051
    depends_on:
      - mysql-server
    networks:
      - zabbix-network

  # Interface Web
  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server-mysql
      PHP_TZ: ${ZBX_WEB_TZ}
    ports:
      - ${ZBX_WEB_PORT}:8080
      - 443:8443
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    networks:
      - zabbix-network

  # Banco de armazenamento
  mysql-server:
    container_name: mysql-server
    image: mysql
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge
